name: Telnyx(cypress+cucumber)


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.9.1'
    - name: Install dependencies
      run: npm ci
    - name: Run Cypress Preprocessor
      run: npm run cypress:proc
    - name: Run Cypress Tests
      run: npm run cypress:execution  
    - name: Upload Results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: cucumber-report.html
    - name: Publishing HTML report to Github Actions
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cucumber-report.html
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: always()
      with:
        branch: report-branch 
        folder: reports
        
