name: Telnyx(cypress+cucumber)


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.9.1'
    - name: Install dependencies
      run: npm ci
    - name: Run Cypress Preprocessor
      run: npm run cypress:proc
    - name: Run Cypress Tests
      run: npm run cypress:execution  
    - name: Push to repository
      uses: cpina/github-action-push-to-another-repository@main
      if: always()
      env:
        API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
      with:
        source-file: 'cucumber-report.html'
        destination-github-username: 'txt2021'
        destination-repository-name: 'Telnyx_Project_cucumber-cypress'
        user-email: txt2021@gmail.com
        target-branch: report-branch
        
